### PR TITLE
WIM Support

### PR DESCRIPTION
**Pull request by ecumber**
I have added support for the Microsoft WIM image format, typically used to deploy Windows installs. It will show information about the WIM itself and the images contained inside it.

I have not tested on other OSes other than Windows, so there may still be bugs, but it seems to work fine on WIMs that I have.

### CODE REVIEW

**Comment by GerbilSoft** [comment]
I hadn't considered adding WIM format,

**Comment by GerbilSoft** [comment]
...and somehow while typing that comment, I pressed some random key that automatically submitted the comment and closed the pull request. Oopsies.

Anyways: I hadn't considered adding WIM format before, but I can see how it would be useful. Will take a look at this PR later this week.

**Comment by GerbilSoft** [comment]
One request: Can you branch the WIM patches into a separate branch in your repo, then use git rebase to rebase it on top of my master branch? That'll help to separate the WIM patches from the rest of the recent v2.2.1 commits.

**Comment by GerbilSoft** [comment]
The CodeQL build failed because at least one of the files is including "Wim_structs.h", but the file is named "wim_structs.h". Linux systems have case-sensitive filenames, so you need to change the include to use lower-case.

**Comment by ecumber** [comment]
I have moved the PR to #392.

**Pull request closed without merging**
