### PR TITLE
GameBoy ROM support

### PR DESCRIPTION
**Pull request by DankRank**
Added support for GameBoy ROMs (includes GameBoy Color and Super GameBoy)

### CODE REVIEW

**Comment by Techokami** [comment]
Awesome, I was hoping for GameBoy support! Now you just need something for an icon. Even if it's something generic.

**Comment by GerbilSoft** [comment]
Generic filetype icons aren't in the scope of the project.

Then again, maybe that could be added later on...

**Comment by Techokami** [comment]
Well I mean, at least as a placeholder. Combined with the fact that some games use the exact same ROM data for all regions, and that there isn't a solid database of GameBoy cart images, would make things tricky for this platform.

**Comment by GerbilSoft** [comment]
Placeholders would be generic icons set in the registry and/or installed in /usr/share/icons . Returning a placeholder icon in the thumbnail generation function would cause problems later on.

In any case, generic icons won't be part of the initial release. If I can get a good set at decent sizes, I'll look into adding them later. (PNG format for Linux; 256-color and 32-bit color ICO for Windows.)

**Comment by GerbilSoft** [comment]
This issue was moved to GerbilSoft/rom-properties#1

**Pull request merged**
