### PR TITLE
EXE NE: Entries tab

### PR DESCRIPTION
**Pull request by DankRank**
Don't really wanna do imports right now.

Also, the second commit needs testing, I don't have any visual basic programs

### CODE REVIEW

**Comment by GerbilSoft** [comment]
I tried out this branch. Valgrind is showing memory issues, and running rpcli on enough NE executables causes memory corruption.

I've attached Windows 3.1's 8514.DRV, which shows the Valgrind issue: [8514.DRV.zip](https://github.com/GerbilSoft/rom-properties/files/9592605/8514.DRV.zip)

Some basic debugging showed that both read_size and nameTable_size were both 21, which is smaller than it should be. In particular, read_size should be larger than nameTable_size, since it has the modref table, too.

Without this branch, read_size == 296, nameTable_size == 292, and nameTable starts at 4.

**Comment by DankRank** [comment]
The 296 read_size you get in master is due to this heuristic:
```
                // Add 256 bytes for the nametable, since we can't determine how
                // big the nametable actually is without reading it.
                read_low_addr = modRefTable_addr;
                nameTable_size = (9 * (static_cast<uint32_t>(modRefs) + 2)) + 256;
                read_size = (importNameTable_addr - modRefTable_addr) + nameTable_size;
```

Here's how the tables actually look in the file:
```
0x80+0x0678 - mod ref table:
dw 0001h
dw 000Ah
0x80+0x067c - import name table:
db 00h
db 08h, "KEYBOARD"
db 06h, "KERNEL"
0x80+0x068d - entry table
```

So the read_size of 21 is justified. The actual problem here was that I calculated nameTable_size wrong, I did `entryTable_addr - modRefTable_addr` instead of `entryTable_addr - importNameTable_addr`.

**Comment by DankRank** [comment]
Added my std::span impl, and also module name/description fields
Example:
```
Module Name:        'DISPLAY'
Module Description: '96 or 120 DPI - IBM 8514 Display Adapter at 1024 by 768'
```

**Comment by GerbilSoft** [comment]
Merged. I needed to add a few workarounds for MSVC 2015 and early releases of 2017 (≤19.14), and disable an assert that no longer seems to apply, but other than that, it looks good. afl-fuzz didn't find any issues with the set of Windows 3.1 executables I tested.

**Pull request merged**
