### PR TITLE
WIM Support

### PR DESCRIPTION
**Pull request by ecumber**
See #391

### CODE REVIEW

**Comment by GerbilSoft** [comment]
Thanks for rebasing; will take a closer look at it sometime later this week.

**Comment by GerbilSoft** [comment]
I made some adjustments to improve reliability and performance, and added `application/x-ms-wim` to xdg/mime.no-thumbnail.types so Linux desktop environments will know to use rom-properties for WIM images.

Merged to master; please test it to make sure everything works as expected. The only WIM images I have on hand are for Windows 7 SP1, and they seemed to work correctly.

**Comment by ecumber** [comment]
For most of the WIMs I have laying around, it works flawlessly, however the maximum characters that the (Display)Name and (Display)Description fields can hold should be limited to <= 260 characters. Anything that exceeds that amount will crash the ListView field on Windows. This can happen with debug builds of Windows which display every possible edition of Windows that can be installed, often exceeding the 260 character limit for ListView items.

**Comment by GerbilSoft** [comment]
That actually affects anything that uses ListView (i.e. any RomData subclass with RFT_LISTDATA), so I'll add something to the Windows UI frontend to truncate any ListView string longer than 260 characters (and add "..." to indicate the string is longer than what's displayed).

The crash is caused by tcscpy_s() throwing an assertion due to the source string being larger than plvItem->cchTextMax (260). Using tcsncpy_s() with _TRUNCATE as the source count value will prevent the assertion and truncate the string. (This is separate from the "..." truncation, just in case cchTextMax happens to be *less* than 260 for some reason.)

Neither GTK nor Qt have the same limitation as far as I know.

**Pull request merged**
