### PR TITLE
Virtual Boy ROM Support

### PR DESCRIPTION
**Pull request by DankRank**
Added support for VB ROMs. Tested with no-intro romset.

### CODE REVIEW

**Comment by GerbilSoft** [comment]
This PR can't be accepted as-is right now:
* I'm not adding code to check anything but the file header in the current version. Anything else can add latency to the file browser.
* The isRomSupported_static() function is simply checking if the file is 512 KB, 1 MB, or 2 MB. That will lead to *lots* of false positives. (I did add some preliminary support for checking file extensions, but it isn't fully implemented at the moment.)

**Comment by DankRank** [comment]
@GerbilSoft Regarding your second point: the thing I did in 2nd commit does seem like the best possible solution for the no-magic formats, without relying on filename, so there's not really anything to do besides extension checking.

Here are some false-positive/performance improvements that could be done for VB and any future no-magic/footer formats:

- Make the heur detection even more stricter at cost of homebrew compatibility.
- As you have mentioned, restrict no-magic formats to a known extension.
- Don't check file for formats that are incapable of doing required thing. I.e. when generating thumbnails, don't try to detect a file as MD/GB/VB/etc, as those don't have any kind of image output (as of right now). This would reduce load time, especially for any footer formats which require special detection. We could use a static function to detect if a class supports a feature.
- In this case, it's possible to eliminate most of the files just from knowing the size. We could make the `isRomSupported_static` (used by factory) only check for the filesize, while the non-static `isRomSupported` (used by the class constructor) could do a more detailed check, taking the footer data from internal buffer.

Any other ideas?

**Comment by GerbilSoft** [comment]
I changed all of the "supported" functions to use the static+virtual pattern, so they can be called without an instance and with an instance.

RomDataFactory::getInstance() now takes an optional thumbnail parameter. If set, it skips over all RomData classes that have no images. (supportedImageTypes() returns 0.)

I'll look into the other optimizations later. You may want to open an actual issue for those instead of simply commenting here.

**Comment by GerbilSoft** [comment]
Reopened and retargetted for 0.9.

**Comment by DankRank** [comment]
This is pretty much finished now, I will need to do some testing, though.

**Comment by DankRank** [comment]
Added some unrelated bugfixes, because why not. I'll test the VirtualBoy roms tonight.

**Comment by GerbilSoft** [comment]
For compatibility reasons, static_assert() is defined as switch() if the compiler doesn't natively support it... but since I raised the minimum compilers to gcc-4.5 and MSVC 2010, that is no longer needed, so static_assert() in the struct headers is fine.

I'll go over this tonight.

**Comment by GerbilSoft** [comment]
Had to fix up a ton of ROM detection stuff, but it all works now. Relaxed the detection code a bit so homebrew ROMs are detected now.

Also added ID6 display.

**Comment by GerbilSoft** [comment]
This issue was moved to GerbilSoft/rom-properties#8

**Pull request merged**
